Web_Sitesi2/Web_Sitesi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Sitesi.Models;

namespace Web_Sitesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            Kitap o1 = new Kitap();
            string anasayfa = "anasayfa";
            o1.kitabim = dbc.tablo2.Where(x=>x.kategori.ToUpper()==anasayfa.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult İletisim()
        {
            return View();
        }
        [HttpPost]
        public ActionResult İletisim(FormCollection form)
        {
            KayitİslemDBEntities2 db = new KayitİslemDBEntities2();
            iletisim model = new iletisim();
            model.ad = form["ad"].Trim();
            model.e_mail = form["email"].Trim();
            model.konu = form["konu"].Trim();
            model.mesaj = form["mesaj"].Trim();
            db.iletisim.Add(model);
            db.SaveChanges();
            return View();
        }
        public ActionResult Yeni_Kitap()
        {
            Kitap o1 = new Kitap();
            o1.kitabim = dbc.tablo2.ToList();
            return View(o1);
        }
        public ActionResult Kitap_icerik(int ? id)
        {
            tablo2 kitabim = dbc.tablo2.Find(id);
            return View(kitabim);
        }
        public ActionResult Hakkımızda()
        {
            return View();
        }
        public ActionResult Giris_Yap()
        {
            return View();
        }
        public ActionResult Tarih()
        {
            Kitap o1 = new Kitap();
            string tarih = "tarih";
            o1.kitabim = dbc.tablo2.Where(x => x.kategori.ToUpper() == tarih.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult Bilim()
        {
            Kitap o1 = new Kitap();
            string bilim = "bilim";
            o1.kitabim = dbc.tablo2.Where(x => x.kategori.ToUpper() == bilim.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult Macera()
        {
            Kitap o1 = new Kitap();
            string macera = "macera";
            o1.kitabim = dbc.tablo2.Where(x => x.kategori.ToUpper() == macera.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult Polisiye()
        {
            Kitap o1 = new Kitap();
            string polisiye = "polisiye";
            o1.kitabim = dbc.tablo2.Where(x => x.kategori.ToUpper() == polisiye.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult Korku()
        {
            Kitap o1 = new Kitap();
            string korku = "korku";
            o1.kitabim = dbc.tablo2.Where(x => x.kategori.ToUpper() == korku.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult Populer()
        {

            Kitap o1 = new Kitap();
            string populer = "popüler";
            o1.kitabim = dbc.tablo2.Where(x => x.kategori.ToUpper() == populer.ToUpper()).ToList();
            return View(o1);
        }
        public ActionResult Cikis()
        {
            Session["kadi"] = null;
            return RedirectToAction("Index", "Home");
        }
         private KayitİslemDBEntities2 dbc = new KayitİslemDBEntities2();
        public ActionResult Giris_Yap2()
        {
            return View();
        }
        public ActionResult Dil()
        {
            return View();
        }
        public ActionResult Admin_Sayfasi()
        {
            return View();
        }
        public ActionResult Firsatlar()
        {
            Kitap o1 = new Kitap();
            o1.kitabim = dbc.tablo2.ToList();
            return View(o1);
        }
        public ActionResult Kayit_Ol()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Kayit_Ol(FormCollection form)
        {
            KayitİslemDBEntities2 db = new KayitİslemDBEntities2();
            tablo model = new tablo();
            model.Ad = form["ad"].Trim();
            model.email = form["email"].Trim();
            model.kadi = form["kullanici_adi"].Trim();
            model.sifre = form["sifre"].Trim();
            model.sifre_tekrar = form["sifre_tekrar"].Trim();
            if (model.sifre!=model.sifre_tekrar)
            {
                Response.Write("<script>alert('Sifreler Uyuşmuyor')</script>");
                return View();
            }
                db.tablo.Add(model);
                db.SaveChanges();
                return View();
        }
        [HttpPost]
        public ActionResult Giris_Yap2(tablo Model, FormCollection form)
        {
            var KULLANICI = dbc.tablo.FirstOrDefault(x=>x.kadi==Model.kadi&&x.sifre==Model.sifre);
            string kullanici_adi = form["kadi"].Trim();
            string sifre = form["sifre"].Trim();
            if (kullanici_adi =="asd" && sifre =="asd")
            {
                Session["Admin"] = "1";
                return RedirectToAction("Admin_Sayfasi","Home");
            }
            else if(KULLANICI!=null)
            {
                Session["kadi"] = KULLANICI;
                return RedirectToAction("Index", "Home");
            }
            Response.Write("<script>alert('Kullanıcı Adını veya Sifreyi Yanlis Girdiniz')</script>");
            return View();
        }
        public class Kitap
        {
        public List<tablo2> kitabim { get; set; }
        }
    }
}

Web_Sitesi2/Web_Sitesi/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Web_Sitesi.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Change(String languageSelect)
        {
            if (languageSelect != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageSelect);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(languageSelect);
            }

            HttpCookie cookie = new HttpCookie("language");
            cookie.Value = languageSelect;
            Response.Cookies.Add(cookie);

            return RedirectToAction("Index","Home");
        }
    }
}

Web_Sitesi2/Web_Sitesi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web_Sitesi2/Web_Sitesi/Views/Home/Admin_Sayfasi.cshtml
@{
    ViewBag.Title = "Admin_Sayfasi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Scripts/Stil.css" rel="stylesheet" />
<a href="/Admin/KitapIndex" style="color:#1E90FF;
  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  font-weight:bold;
  font-size:20px;">KAYIT EKLE/SİL</a>
<br />
<br />

<a href="/Admin/Kitap2Index" style="color:#1E90FF;
  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  font-weight:bold;
  font-size:20px;">YORUM VE FOTOĞRAF EKLE SİL</a>

Web_Sitesi2/Web_Sitesi/Views/Home/Cikis.cshtml
@model Web_Sitesi.Models.tablo

@{
    ViewBag.Title = "Cikis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Cikis Yaptiniz</h2>

Web_Sitesi2/Web_Sitesi/Views/Home/Dil.cshtml
@{
    ViewBag.Title = "Dil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Scripts/Stil.css" rel="stylesheet" />
@Html.ActionLink("English", "Change", "Language",new { languageSelect = "en"},new{style="color:#1E90FF;"})
<br />
@Html.ActionLink("Türkçe", "Change", "Language", new { languageSelect = "tr" },new {style="color:#1E90FF;"})

Web_Sitesi2/Web_Sitesi/Views/Home/Firsatlar.cshtml
@model Web_Sitesi.Controllers.HomeController.Kitap
@{
    ViewBag.Title = "Firsatlar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <h1 style="color: #1E90FF; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;font-weight:bold;font-size:40px;">Müthiş Fırsatlar Sizlerle</h1>
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="container">
        <div class="row">
            @foreach (var item in Model.kitabim)
            {
                <div class="col-sm-3">
                    <div class="thumbnail">
                        <a href="/Home/Kitap_icerik/?id=@item.resim_id" class="">
                            <div class="caption">
                                <img src="~/Scripts/indirim.png" style="width:100px;" />
                                <h4 class="" style="color:#1E90FF;  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        font-weight:bold; ">@item.kadi</h4>
                            </div>
                            <img src="@item.resim" class="" style="height:180px;width:150px">
                        </a>
                    </div>
                </div>
            }
            <!-- TH1 -->
           
         <!-- TH6 -->
        </div><!--/row -->
    </div>
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Giris_Yap.cshtml
@{
    ViewBag.Title = "Giris_Yap";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" href="css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Lütfen Giris Yapınız</h3>
                    </div>
                    <div class="panel-body">
                        <form accept-charset="UTF-8" role="form" action="/Login/Admin" method="post">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail veya Kullanıcı Adı" name="kadi" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Sifre" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                                    </label>
                                </div>
                                <input class="btn btn-lg btn-block" type="submit" value="Giris Yap">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Giris_Yap2.cshtml
@model Web_Sitesi.Models.tablo

@{
    ViewBag.Title = "Giris_Yap2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Hata</h2>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" href="css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Lütfen Giris Yapınız</h3>
                    </div>
                    <div class="panel-body">
                        <form accept-charset="UTF-8" role="form" method="post">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail veya Kullanıcı Adı" name="kadi" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Sifre" name="sifre" type="password" value="">
                                </div>
                                <input class="btn btn-lg btn-block" type="submit" value="Giris Yap">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Hakkımızda.cshtml
@{
    ViewBag.Title = "Hakkımızda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" href="css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Hakkımızda</h3>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1"><h3>ARSİV KİTABEVİ Marka Vizyonu</h3>
Herkesi, kültür ve eğlence dünyasının sunduğu zenginlikleri daha sık, daha kolay ve daha nitelikli bir şekilde keşfetmeye, keyfini çıkarmaya ve paylaşmaya teşvik eden, böylece insanları ortak bir platformda biraraya getiren ve hayatın her anını zenginleştiren bir dünya.

<h3>ARSİV KİTABEVİ Marka Misyonu</h3>
ARSİV KİTABEVİ, evrensel ürün yelpazesi ve hizmet anlayışı ile her müşterisine, kültür ve eğlence ürünlerine ulaşmanın ve bunun keyfini çıkarmanın eşsiz deneyimini her zaman ve her yerde yaşatır.

<h3>Tarihçe</h3>
ARSİV KİTABEVİ, 1996 yılının Kasım ayında kuruldu ve ilk mağazasını 1997 yılının Mayıs ayında Erenköy'de açtı. Türkiye genelinde 26 ilde 147 mağazası bulunan ARSİV KİTABEVİ sektöründe pazar liderliğini sürdürüyor. Kitaptan müziğe, filmden elektroniğe, oyundan hobiye, hediyelik eşyadan kırtasiyeye, geniş ürün seçenekleri sunan ARSİV KİTABEVİ, toplumu kitap okumaya, müzik dinlemeye, film izlemeye özendirerek üstlendiği sosyal sorumluluk görevini de yerine getiriyor. ARSİV KİTABEVİ, eğlence ve kültür ürünleriyle tüketiciyi buluşturarak, okuyan ve dinleyen bir Türk toplumunun oluşumuna katkıda bulunuyor. Her geçen gün bir yenisi açılan ARSİV KİTABEVİ mağazaları, şehirlerin işlek caddeleri ile Türk ve dünya markalarının buluştuğu modern alışveriş merkezlerinde yer alıyor.

ARSİV KİTABEVİ 2004 yılında yeni mağazacılık anlayışı getirerek mağaza standartlarını geliştirdi.

Ankara Tunalı, İzmir Forum Bornova ve Kanyon mağazaları ile mega mağazacılık alanında büyük adımlar attı, hem dekorasyonu, hem cafeleri ile Avrupa'daki örneklerini aratmayacak mekanlar yarattı. ARSİV KİTABEVİ, kültür, sanat, eğlence konusunda geniş bir ürün yelpazesini modern ve dinlendirici bir atmosfer içerisinde sunan Türkiye'nin tek perakende zinciri olarak, cafeleri, dinleme kuleleri, okuma alanları, sanatçılarla hayranlarını buluşturan ve artık gelenek haline gelen imza günleri, partiler, galalar, ürün lansmanları ile klasik mağaza konseptinin dışında hizmet anlayışı geliştirdi.</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Index.cshtml
@model Web_Sitesi.Controllers.HomeController.Kitap
@{
    ViewBag.Title = "Home Page";
    Scripts.Render("~/bundles/jquery");
    Scripts.Render("~/bundles/bootstrap");
    Styles.Render("~/Content/css");
    Scripts.Render("~/bundles/modernizr");
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <br>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active" style="background-color:#F0F8FF;">
                    <a href="#"><img class="slayt_ayar" src="~/Scripts/5.jpg"  alt="Chania" width="460" height="345"></a>
                    <div class="carousel-caption">
                        <h3>ASSASINS CREED YENİ KİTABI GELDİ.</h3>
                        <p style="font-weight:bold;color:white;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">Assasins Creed serisi devam ediyor.Serinin devamı geldikçe kitapları buradan paylaşıyoruz...</p>
                    </div>
                </div>
                <div class="item" style="background-color:#F0F8FF;">
                    <a><img class="slayt_ayar" src="~/Scripts/7.jpg"alt="Chania" width="460" height="345"></a>
                    <div class="carousel-caption">
                        <h3>BATMAN CREED YENİ KİTABI GELDİ.</h3>
                        <p style="font-weight:bold;color:white;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"></p>
                    </div>
                </div>

                <div class="item" style="background-color:#F0F8FF;">
                    <img class="slayt_ayar"src="~/Scripts/yeni1.jpg" alt="Flower" width="460" height="345">
                    <div class="carousel-caption">
                        <h3></h3>
                        <p style="font-weight:bold;color:white;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"></p>
                    </div>
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="background-color:#87CEFF;">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="background-color:#87CEFF;">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="container">
        <div class="row">
            <!-- TH1 -->
        @foreach (var item in Model.kitabim)
        {
            <div class="col-sm-3">
                <div class="thumbnail">
                    <a href="/Home/Kitap_icerik/?id=@item.resim_id" class="">
                        <div class="caption">
                            <h4 class="" style="color:#1E90FF;  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        font-weight:bold; ">@item.kadi</h4>
                        </div>
                        <img src="@item.resim" class="" style="height:180px;width:150px" />
                    </a>
                </div>
            </div>
        }

        </div><!--/row -->
    </div> <!-- end container -->
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Kayit_Ol.cshtml
@{
    ViewBag.Title = "Kayit_Ol";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Scripts.Render("~/bundles/jquery");
    Scripts.Render("~/bundles/bootstrap");
    Styles.Render("~/Content/css");
    Scripts.Render("~/bundles/modernizr");
}

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" href="css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading" style="background-color:#1E90FF; color:white;">
                        <h3 class="panel-title">Kayıt Ol</h3>
                    </div>
                    <div class="panel-body">
                        <form accept-charset="UTF-8" role="form" method="post">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Adınız" name="ad" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-Mail" name="email" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Kullanıcı Adı" name="kullanici_adi" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Sifre" name="sifre" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Sifre Tekrar" name="sifre_tekrar" type="password" value="">
                                </div>
                                <div class="checkbox">
                                </div>
                                <input class="btn btn-lg btn-block" type="submit" value="Kayıt Ol">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Kitap_icerik.cshtml
@model Web_Sitesi.Models.tablo2
@{
    ViewBag.Title = "Kitap_icerik";
    Layout ="~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css">
    <!-- Website CSS style -->
    <link rel="stylesheet" href="css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css">
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="@Model.resim" style="height:600px;" />
            </div>
            <div class="col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">@Model.kadi</h3>
                        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
                    </div>
                    <div class="panel-body">@Model.icerik</div>
                </div>
            </div>
            <link rel="stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css">
            @if (Session["kadi"] != null)
            {
                
            <div class="container">
                <div class="row">

                    <div class="col-md-6">
                        <div class="widget-area no-padding blank">
                            <div class="status-upload">
                                <form>
                                    <textarea placeholder="What are you doing right now?" name="yorum"></textarea>
                                    <button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> Share</button>
                                </form>
                            </div><!-- Status Upload  -->
                        </div><!-- Widget Area -->
                    </div>

                </div>
            </div>

            }
            else
            {
            <h2>Üye Olmadan Yorum Yapılamamaktadır</h2>
            }
        </div>
    </div>
           
</body>
</html>

Web_Sitesi2/Web_Sitesi/Views/Home/Macera.cshtml
@model Web_Sitesi.Controllers.HomeController.Kitap
@{
    ViewBag.Title = "Firsatlar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <link href="~/Scripts/Stil.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <h1 style="color: #1E90FF; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;font-weight:bold;font-size:40px;">Macera</h1>
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="container">
        <div class="row">
            @foreach (var item in Model.kitabim)
            {
                <div class="col-sm-3">
                    <div class="thumbnail">
                        <a href="/Home/Kitap_icerik/?id=@item.resim_id" class="">
                            <div class="caption">
                                <h4 class="" style="color:#1E90FF;  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        font-weight:bold; ">@item.kadi</h4>
                            </div>
                            <img src="@item.resim" class="" style="height:180px;width:150px">
                        </a>
                    </div>
                </div>
            }
            <!-- TH1 -->
            <!-- TH6 -->
        </div><!--/row -->
    </div>
</body>
</html>